language: bash
os:
- linux
- osx

script:
- bash -c 'time bin/bats --tap test'
- shellcheck $(git diff --name-only -- $TRAVIS_COMMIT_RANGE)

addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck

notifications:
  email:
    on_success: never
